spring:
  application:
    name: ${project.artifactId}
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12 
    key-store: classpath:keystore.p12
    key-store-password: example
    key-alias: tomcat